const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const nodes=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',insertAdjacentHTML(position,html){this.innerHTML=position==='afterbegin'?html+this.innerHTML:this.innerHTML+html},classList:{add(){},remove(){},toggle(){}},querySelectorAll(){return[]},querySelector(){return node('nested')},setAttribute(){}});return nodes.get(id)};
const context=vm.createContext({document:{getElementById:node,querySelector:()=>node('nested'),querySelectorAll:()=>[],addEventListener(){}},window:{matchMedia:()=>({matches:true})},localStorage:{getItem:()=>null,setItem(){}},sessionStorage:{getItem:()=>null},location:{hash:'#home'},URLSearchParams,Set,Map,innerWidth:390,console});
const run=code=>vm.runInContext(code,context);for(const f of ['catalog.js','spec-data.js'])run(fs.readFileSync('storefront/'+f,'utf8'));
let app=fs.readFileSync('storefront/app.js','utf8');run(app.slice(0,app.indexOf("document.getElementById('bagButton').onclick")));
run('const reduceMotion=()=>true;let disposeStorefront=()=>{};');
let features=fs.readFileSync('storefront/shop-features.js','utf8');run(features.slice(0,features.indexOf("document.querySelector('nav').insertAdjacentHTML")));
assert.equal(run("phoneProducts().length"),14);assert.equal(run("phoneProducts().every(p=>phoneSpecs[p.id]?.sources.length&&Object.keys(phoneSpecs[p.id].groups).length===6)"),true);
assert.equal(run("new Set(products.map(p=>p.id)).size===products.length"),true);
assert.equal(run("filters.budget=60000;filtered().every(p=>p.price<=60000)"),true);
assert.equal(run("filters.budget=300000;filters.storage='1TB';filtered().every(p=>p.storage?.includes('1TB'))"),true);
run("filters.storage='All';wishes.add('pixel-11');filters.saved=true");assert.equal(run('filtered().length'),1);assert.equal(run('filtered()[0].id'),'pixel-11');run('filters.saved=false');
run("paintSpecRows([phoneById('iphone-18-pro'),phoneById('iphone-18-pro-max')])");assert.match(node('specRows').innerHTML,/6.3 inches/);assert.match(node('specRows').innerHTML,/6.9 inches/);
run("compareState.differences=true;paintSpecRows([phoneById('iphone-18-pro'),phoneById('iphone-18-pro-max')])");assert.doesNotMatch(node('specRows').innerHTML,/Apple A20 Pro/);assert.match(node('specRows').innerHTML,/249 g/);
run("compareState.search='aperture';compareState.differences=false;paintSpecRows([phoneById('iphone-18-pro'),phoneById('galaxy-s26-ultra')])");assert.match(node('specRows').innerHTML,/variable aperture/);assert.doesNotMatch(node('specRows').innerHTML,/Wi-Fi/);
const html=run("card(phoneById('pixel-11'))");assert.match(html,/data-wish="pixel-11"/);assert.match(html,/data-compare="pixel-11"/);
for(const p of run('products'))assert.ok(fs.existsSync('storefront/assets/'+p.image),p.image);
const postcss=require('../node_modules/.pnpm/'+fs.readdirSync('node_modules/.pnpm').find(n=>n.startsWith('postcss@'))+'/node_modules/postcss');for(const f of ['liquid-glass.css','shop-features.css'])postcss.parse(fs.readFileSync('storefront/'+f,'utf8'),{from:f});
console.log('Passed: 14 sourced phone datasets, filters, wishlist selection, difference/search tables, product controls, image paths and CSS parsing.');
