import {getChatGPTUser} from '../../chatgpt-auth';
import {getDb} from '../../../db';
import {demoOrders,inventory} from '../../../db/schema';
import {sameOrigin} from '../../../lib/shop-auth';
import catalogue from '../../../lib/catalogue.json';
import {eq,desc,and,gte} from 'drizzle-orm';
export const dynamic='force-dynamic';
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in required'},{status:401});return Response.json({orders:await getDb().select().from(demoOrders).where(eq(demoOrders.userId,user.userId)).orderBy(desc(demoOrders.createdAt)).limit(20)},{headers:{'Cache-Control':'no-store'}})}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user||!sameOrigin(request))return Response.json({error:'Sign in required'},{status:401});if(Number(request.headers.get('content-length'))>12000)return Response.json({error:'Too large'},{status:413});let data: {items:Array<{id:string;qty:number;variant:string}>;area:string};try{data=await request.json() as typeof data}catch{return Response.json({error:'Invalid JSON'},{status:400})}if(!Array.isArray(data.items)||!data.items.length||data.items.length>30)return Response.json({error:'Invalid bag'},{status:400});const db=getDb();const recent=await db.select().from(demoOrders).where(and(eq(demoOrders.userId,user.userId),gte(demoOrders.createdAt,new Date(Date.now()-60000).toISOString())));if(recent.length>=3)return Response.json({error:'Please wait a minute before another demo checkout'},{status:429});const overrides=await db.select().from(inventory);let total=0;const items=[];for(const x of data.items){const p=catalogue.find(p=>p.id===x.id);if(!p||!Number.isInteger(x.qty)||x.qty<1||x.qty>20||typeof x.variant!=='string'||x.variant.length>160)return Response.json({error:'Invalid item'},{status:400});const storage=(p as {storage?:string[]}).storage||[];let idx=storage.findIndex(s=>x.variant.startsWith(s+' · '));if(p.category==='Phones'&&idx<0)return Response.json({error:'Invalid phone storage'},{status:400});const price=(overrides.find(o=>o.id===p.id)?.price??p.price)+Math.max(0,idx)*18000;items.push({id:p.id,name:p.name,variant:x.variant,qty:x.qty,price});total+=price*x.qty}const delivery=data.area==='outside'?150:80;total+=delivery;const id='KW-DEMO-'+crypto.randomUUID().slice(0,8).toUpperCase();await db.insert(demoOrders).values({id,userId:user.userId,items:JSON.stringify(items),total,status:'Demo received',createdAt:new Date().toISOString()});return Response.json({id,total,delivery,status:'Demo received',demo:true},{status:201})}
